### ISSUE TITLE
/live URL not supported

### ISSUE THREAD

**Issue by GammelSami** [gifnksm/youtube_thumbnail_viewer#5]
Example: https://www.youtube.com/c/LofiGirl/live

**Comment by GammelSami** [comment]
A bit trickyer than my last issue because you cant extract the video-id from url. 
But looks like on livestreams `document.querySelector('link[rel="image_src"]');` always returns the thumbnail url.

**Comment by gifnksm** [comment]
Thank you for filing an issue, and suggesting how to fix it!
Version 0.3.0 with support for `/live` URLs has been released at [addons.mozilla.org](https://addons.mozilla.org/ja/firefox/addon/youtube-thumbnail-viewer/).

In this release, I have changed the way to get thumbnails from OGP metadata instead of from URLs. This change was inspired by your suggestion; OGP is a common way to get web page metadata, and I expect it to work for more web pages.

I have confirmed that the thumbnails will show up on YouTube and YouTube Music, but if you have any issues, please feel free to open an issue.
